#make sure you BUILD your TS files first with 'npm run build' | colyseus-k8:0.14.8.HPG for hammerplay with clear node modules function
version: '3.8'

services:
  colyseus_server:
    build: 
      context: .
      target: prod
    image: lucidsightinc/colyseus-k8-node16.15.0-buster-uws_ws-redis:0.14.25
    ports:
      - "2567:2567"
      - "9229:9229"
    volumes:
      - ./server/arena:/colyseus/app/server/arena
